# Generated by Django 5.0.14 on 2025-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_alter_subscription_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
