# Generated by Django 5.0.14 on 2025-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_alter_subscription_options_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
