# Generated by Django 5.0.14 on 2025-06-11 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0011_subscriptionprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={"ordering": ["order", "featured", "-updated"]},
        ),
    ]
