# Generated by Django 5.0.14 on 2025-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0014_alter_subscriptionprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="List of features for this subscription plan, use markdown syntax",
                null=True,
            ),
        ),
    ]
